services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    restart: always
    networks:
      - dbnet
    expose:
      - 8088
    ports:
      - "80:8088"
      - "443:443"
    volumes:
      - ./driveparts/static:/app/www/driveparts/static
      - ./driveparts/media:/app/www/driveparts/media
      - ./driveparts/logs:/app/www/driveparts/logs
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - driveparts
  driveparts:
    build: ./driveparts
    image: driveparts
    container_name: driveparts
    restart: always
    # command: gunicorn -c -gunicorn.py candystore.wsgi
    command: "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    links:
      - "postgres:dbps"
    ports:
      - "8000:8000"
    networks:
      - dbnet
    volumes:
      - ./driveparts:/app/www/driveparts

    depends_on:
      - postgres
    
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    links:
      - "postgres:db"
    networks:
      - dbnet
    depends_on:
      - postgres
      
  postgres:
    image: postgres:17-alpine
    container_name: psgr
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    networks:
      - dbnet
  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   command: certonly --webroot --webroot-path=/var/www/certbot --email tsoloevalan@gmail.com --agree-tos -d drive-parts-store.ru  --keep-until-expiring
  #   depends_on:
  #     - nginx
      

networks:
  dbnet:
    driver: bridge

volumes:
  postgres-data:
      