# Generated by Django 5.1.2 on 2025-03-10 13:57

import django.db.models.deletion
import django_extensions.db.fields
import goods.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Имя')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='tag')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload_model')),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Фото')),
                ('desc', models.TextField(blank=True)),
                ('status', models.BooleanField(default=0, verbose_name=goods.models.Goods.Status)),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to=settings.AUTH_USER_MODEL)),
                ('cats', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods', to='goods.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='gtags', to='goods.tags')),
            ],
            options={
                'verbose_name': 'Авто товары',
                'verbose_name_plural': 'Авто товары',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='goods_goods_time_cr_cf3877_idx')],
            },
        ),
    ]
